

- id: demo1
  desc: One set of experiments (with length=5)
  code:
  - diffeoplan.DiffeoplanBatch
  - algorithms:
    - random1
    - random2
    testcases:
    - tc_dcam1_lena_d5_*
    discdds: tc_dcam1


- id: demo2
  desc: Another independent set of experiments (with length=10)
  code:
  - diffeoplan.DiffeoplanBatch
  - algorithms:
    - random1
    - random2
    testcases:
    - tc_dcam1_lena_d10_*
    discdds: tc_dcam1


- id: demo3
  desc: Tests for graphsearch
  code:
  - diffeoplan.DiffeoplanBatch
  - algorithms:
    - graphsearch_breadth_3
    testcases:
    - tc_dcam1_lena_d10_*
    discdds: tc_dcam1
  

- id: struct_torus1_d10
  desc: Test stuructured search. 
  code:
  - diffeoplan.DiffeoplanBatch
  - algorithms:
    - structured_breadth_20
    testcases:
    - tc_dtx2_lena_d10_*
    discdds: tc_dcam1
  